### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ZxFrankxZ** [iSanjayAchar/node-yt#1]
/rbd/pnpm-volume/4da950e4-7e87-4872-95f8- 
        088ef3c8efac/node_modules/.registry.npmjs.org/node-yt/1.0.8/node_modules/node-yt/script.js:110

        callback(body.items[0].contentDetails.relatedPlaylists.uploads)

                           ^

         TypeError: Cannot read property '0' of undefined

**Comment by DaggieBlanqx** [comment]
This error happens when their is an issue with your api-key.
To resolve it , check whether the API-Key is :
1.Correct
2.Project is valid in Google Developer Console 
3.The project in Google Developer Console has not been scheduled for deletion.

 ```
//you can modify your code as below to get a console.log of an issue
request(options, (err, resp, body) => {
        body = JSON.parse(body);
        if (body.error) {
            //api key issues are here
            console.log(body.error.message);
        }else{
            callback(body.items[0].contentDetails.relatedPlaylists.uploads);
        }
    })
```
